In [ ]:
#Task
#Andrea has a simple equation:
                    #Y = a + b1*f1 + b1*f2 + ... + bm*fm
#for (m+1) real constants (a, f1, f2,... , fm). We can say that the value of Y depends on m features. Andrea 
#studies this equation for n different feature sets (f1, f2, f3,..., fm) and records each respective value of Y. 
#If she has q new feature sets, can you help Andrea find the value of Y for each of the sets?
#Note: You are not expected to account for bias and variance trade-offs.

In [1]:
import numpy as np

In [3]:
m,n = [int(i) for i in input().strip().split(' ')]

2 7


In [4]:
X = []
Y = []
for i in range(n):
    data = input().strip().split(' ')
    X.append(data[:m])
    Y.append(data[m:])

0.18 0.89 109.85
1.0 0.26 155.72
0.92 0.11 137.66
0.07 0.37 76.17
0.85 0.16 139.75
0.99 0.41 162.6
0.87 0.47 151.77


In [5]:
q = int(input().strip())

4


In [6]:
X_new = []
for x in range(q):
    X_new.append(input().strip().split(' '))

0.49 0.18
0.57 0.83
0.56 0.64
0.76 0.18


In [7]:
X = np.array(X, float)
Y = np.array(Y, float)
X_new = np.array(X_new, float)

In [8]:
#center
X_R = X-np.mean(X,axis=0)
print(X_R)

[[-0.51714286  0.50857143]
 [ 0.30285714 -0.12142857]
 [ 0.22285714 -0.27142857]
 [-0.62714286 -0.01142857]
 [ 0.15285714 -0.22142857]
 [ 0.29285714  0.02857143]
 [ 0.17285714  0.08857143]]


In [9]:
Y_R = Y-np.mean(Y)
print(Y_R)

[[-23.51]
 [ 22.36]
 [  4.3 ]
 [-57.19]
 [  6.39]
 [ 29.24]
 [ 18.41]]


In [10]:
#calculate beta
beta = np.dot(np.linalg.inv(np.dot(X_R.T,X_R)),np.dot(X_R.T,Y_R))
print(beta)

[[90.69331739]
 [46.46296549]]


In [11]:
#predict
X_new_R = X_new-np.mean(X,axis=0)
print(X_new_R)
Y_new_R = np.dot(X_new_R,beta)
print(Y_new_R)
Y_new = Y_new_R + np.mean(Y)
print(Y_new)

[[-0.20714286 -0.20142857]
 [-0.12714286  0.44857143]
 [-0.13714286  0.25857143]
 [ 0.06285714 -0.20142857]]
[[-28.14544165]
 [  9.31095131]
 [ -0.42394531]
 [ -3.65824595]]
[[105.21455835]
 [142.67095131]
 [132.93605469]
 [129.70175405]]


In [12]:
for i in Y_new:
    print(round(float(i),2))

105.21
142.67
132.94
129.7
